services:
  
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault:/vault
    environment:
      - VAULT_ADDR=http://localhost:8200
      - VAULT_TOKEN=root
      - VAULT_CLUSTER_ADDR=http://vault:8201
      - VAULT_CLUSTER_TOKEN=root
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    command: bash -c "apk add --no-cache jq && /vault/start.sh"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - VAULT_CLUSTER_ADDR=http://vault:8201
      - VAULT_CLUSTER_TOKEN=root

  web:
    build: .
    image: zolin17/big-data-3:latest
    container_name: big-data
    depends_on:
      - clickhouse
      - vault
    command: bash -c "
      python src/preprocess.py &&
      python src/train.py &&
      python src/app.py"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    restart: on-failure

volumes:
  clickhouse_data:
  vault_data:
